Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,11 +44,18 @@ jobs:
 
       - name: Validate IPA URL
         run: |
-          curl -L -r 0-10239 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
-          file_type=$(file --mime-type -b sample.part)
-
+          curl -L -o sample.ipa "${{ inputs.ipa_url }}" > /dev/null 2>&1
+          file_type=$(file --mime-type -b sample.ipa)
+      
           if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
-            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
+            echo "::error::Validation failed: The file is not a valid IPA file. Detected MIME type: $file_type."
+            exit 1
+          fi
+      
+          
+          unzip -t sample.ipa > /dev/null 2>&1
+          if [[ $? -ne 0 ]]; then
+            echo "::error::Validation failed: The file is not a valid ZIP archive."
             exit 1
           fi
 
